[package]
name = "text-svg"
version = "0.1.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/matthunz/text-svg"
description = "Render text or glyphs in a font to an SVG path"

[lib]
name = "text_svg"

[dependencies]
rusttype = "0.9.3"
svg = "0.12.1"
